Repository labria/nomic-base, pull requests merged in 2024-06, with the labels that each got.

#2 Why would you say no?
  players.md
Labels: documentation

#7 New Rule: #108 - Earning from Success
  rules.md
Labels: W opinion

#13 Veto Limit
  rules.md
Labels: level 10 rizz

#14 Rule #110: Back to Life
  rules.md
Labels: good first issue, level 10 rizz

#16 Rule 100
  rules.md
Labels: enhancement

#18 115, Third time's the charm
  rules.md
Labels: L rizz
